version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: aws-sdk
    versions:
    - 2.833.0
    - 2.836.0
    - 2.837.0
    - 2.840.0
    - 2.842.0
    - 2.845.0
    - 2.846.0
    - 2.847.0
    - 2.848.0
    - 2.850.0
    - 2.851.0
    - 2.853.0
    - 2.854.0
    - 2.855.0
    - 2.856.0
    - 2.857.0
    - 2.860.0
    - 2.861.0
    - 2.862.0
    - 2.863.0
    - 2.866.0
    - 2.870.0
    - 2.871.0
    - 2.872.0
    - 2.874.0
    - 2.875.0
    - 2.877.0
    - 2.879.0
    - 2.880.0
    - 2.881.0
    - 2.882.0
    - 2.883.0
    - 2.884.0
    - 2.890.0
    - 2.891.0
    - 2.892.0
    - 2.893.0
    - 2.894.0
  - dependency-name: "@types/node"
    versions:
    - 14.14.33
    - 14.14.34
    - 14.14.36
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: "@types/serverless"
    versions:
    - 1.78.24
  - dependency-name: "@aws-amplify/auth"
    versions:
    - 3.4.19
    - 3.4.22
    - 3.4.24
    - 3.4.28
  - dependency-name: amazon-cognito-identity-js
    versions:
    - 4.5.13
    - 4.5.8
    - 4.5.9
  - dependency-name: husky
    versions:
    - 5.1.2
  - dependency-name: typescript
    versions:
    - 4.2.2
